plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

repositories {
    mavenCentral()
}

def loadLocalProperties() {
    // Android Studio creates a local.properties file in the root directory of
    // the project. Since this gradle file is in the default app module, we
    // need to look in the parent directory for the local.properties file.
    def f = file("../local.properties")
    def properties = new Properties()
    if (f.canRead()) {
        f.newReader().withReader {
            properties.load(it)
        }
    }
    return properties
}

def localProperties = loadLocalProperties()

android {
    namespace "com.company.esp32.alerts"
    compileSdk 34

    // Aktiviert die automatische Generierung der BuildConfig-Klasse
    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "com.company.esp32.alerts"
        minSdk 23
        targetSdk 34
        versionCode 6
        versionName = "3.0.3"    // Text-Anzeige: Das ist der String, den du in der App-Verwaltung siehst        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

            if (localProperties.getProperty(
                    "autosignReleaseWithDebugKey", "false").toBoolean()) {
                signingConfig signingConfigs.debug
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    packagingOptions {
        resources {
            excludes += ['META-INF/*']
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    // AndroidX & UI
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.preference:preference-ktx:1.2.1'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'

    // Logging
    implementation 'com.jakewharton.timber:timber:4.7.1'

    // Ktor (Webserver)
    def ktor_version = "1.6.1"
    implementation "io.ktor:ktor:$ktor_version"
    implementation "io.ktor:ktor-server-netty:$ktor_version"
    implementation "io.ktor:ktor-gson:$ktor_version"

    // Dependency Injection
    implementation "io.insert-koin:koin-ktor:3.1.2"

    // preferences
    implementation 'androidx.preference:preference-ktx:1.2.1'

    // Testing
    testImplementation 'junit:junit:4.13.2'
    testImplementation "io.ktor:ktor-server-tests:$ktor_version"
    testImplementation "io.mockk:mockk:1.12.0"
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}